
services:
  posio:
    image: littlestache/posio
    restart: unless-stopped
    volumes:
        - $app_dir_data:/posio
    environment:
        - POSIO_SETTINGS=/app/config.py
          #ports:
          #    - 5000:5000
